#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0864186_SoanDeThi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="0864186_TracNghiem")]
	public partial class _0864186_TracNghiemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCauHoi(CauHoi instance);
    partial void UpdateCauHoi(CauHoi instance);
    partial void DeleteCauHoi(CauHoi instance);
    partial void InsertChuDe(ChuDe instance);
    partial void UpdateChuDe(ChuDe instance);
    partial void DeleteChuDe(ChuDe instance);
    #endregion
		
		public _0864186_TracNghiemDataContext() : 
				base(global::_0864186_SoanDeThi.Properties.Settings.Default._0864186_TracNghiemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public _0864186_TracNghiemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _0864186_TracNghiemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _0864186_TracNghiemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _0864186_TracNghiemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<ChuDe> ChuDes
		{
			get
			{
				return this.GetTable<ChuDe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCauHoi;
		
		private System.Nullable<int> _maChuDe;
		
		private string _noiDung;
		
		private string _dapAnA;
		
		private string _dapAnB;
		
		private string _dapAnC;
		
		private string _dapAnD;
		
		private System.Nullable<int> _dapAnDung;
		
		private EntityRef<ChuDe> _ChuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCauHoiChanging(int value);
    partial void OnmaCauHoiChanged();
    partial void OnmaChuDeChanging(System.Nullable<int> value);
    partial void OnmaChuDeChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OndapAnAChanging(string value);
    partial void OndapAnAChanged();
    partial void OndapAnBChanging(string value);
    partial void OndapAnBChanged();
    partial void OndapAnCChanging(string value);
    partial void OndapAnCChanged();
    partial void OndapAnDChanging(string value);
    partial void OndapAnDChanged();
    partial void OndapAnDungChanging(System.Nullable<int> value);
    partial void OndapAnDungChanged();
    #endregion
		
		public CauHoi()
		{
			this._ChuDe = default(EntityRef<ChuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCauHoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCauHoi
		{
			get
			{
				return this._maCauHoi;
			}
			set
			{
				if ((this._maCauHoi != value))
				{
					this.OnmaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._maCauHoi = value;
					this.SendPropertyChanged("maCauHoi");
					this.OnmaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChuDe", DbType="Int")]
		public System.Nullable<int> maChuDe
		{
			get
			{
				return this._maChuDe;
			}
			set
			{
				if ((this._maChuDe != value))
				{
					if (this._ChuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaChuDeChanging(value);
					this.SendPropertyChanging();
					this._maChuDe = value;
					this.SendPropertyChanged("maChuDe");
					this.OnmaChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dapAnA", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string dapAnA
		{
			get
			{
				return this._dapAnA;
			}
			set
			{
				if ((this._dapAnA != value))
				{
					this.OndapAnAChanging(value);
					this.SendPropertyChanging();
					this._dapAnA = value;
					this.SendPropertyChanged("dapAnA");
					this.OndapAnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dapAnB", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string dapAnB
		{
			get
			{
				return this._dapAnB;
			}
			set
			{
				if ((this._dapAnB != value))
				{
					this.OndapAnBChanging(value);
					this.SendPropertyChanging();
					this._dapAnB = value;
					this.SendPropertyChanged("dapAnB");
					this.OndapAnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dapAnC", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string dapAnC
		{
			get
			{
				return this._dapAnC;
			}
			set
			{
				if ((this._dapAnC != value))
				{
					this.OndapAnCChanging(value);
					this.SendPropertyChanging();
					this._dapAnC = value;
					this.SendPropertyChanged("dapAnC");
					this.OndapAnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dapAnD", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string dapAnD
		{
			get
			{
				return this._dapAnD;
			}
			set
			{
				if ((this._dapAnD != value))
				{
					this.OndapAnDChanging(value);
					this.SendPropertyChanging();
					this._dapAnD = value;
					this.SendPropertyChanged("dapAnD");
					this.OndapAnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dapAnDung", DbType="Int")]
		public System.Nullable<int> dapAnDung
		{
			get
			{
				return this._dapAnDung;
			}
			set
			{
				if ((this._dapAnDung != value))
				{
					this.OndapAnDungChanging(value);
					this.SendPropertyChanging();
					this._dapAnDung = value;
					this.SendPropertyChanged("dapAnDung");
					this.OndapAnDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_CauHoi", Storage="_ChuDe", ThisKey="maChuDe", OtherKey="maChuDe", IsForeignKey=true)]
		public ChuDe ChuDe
		{
			get
			{
				return this._ChuDe.Entity;
			}
			set
			{
				ChuDe previousValue = this._ChuDe.Entity;
				if (((previousValue != value) 
							|| (this._ChuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuDe.Entity = null;
						previousValue.CauHois.Remove(this);
					}
					this._ChuDe.Entity = value;
					if ((value != null))
					{
						value.CauHois.Add(this);
						this._maChuDe = value.maChuDe;
					}
					else
					{
						this._maChuDe = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuDe")]
	public partial class ChuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maChuDe;
		
		private string _tenChuDe;
		
		private EntitySet<CauHoi> _CauHois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChuDeChanging(int value);
    partial void OnmaChuDeChanged();
    partial void OntenChuDeChanging(string value);
    partial void OntenChuDeChanged();
    #endregion
		
		public ChuDe()
		{
			this._CauHois = new EntitySet<CauHoi>(new Action<CauHoi>(this.attach_CauHois), new Action<CauHoi>(this.detach_CauHois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChuDe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maChuDe
		{
			get
			{
				return this._maChuDe;
			}
			set
			{
				if ((this._maChuDe != value))
				{
					this.OnmaChuDeChanging(value);
					this.SendPropertyChanging();
					this._maChuDe = value;
					this.SendPropertyChanged("maChuDe");
					this.OnmaChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChuDe", DbType="NVarChar(MAX)")]
		public string tenChuDe
		{
			get
			{
				return this._tenChuDe;
			}
			set
			{
				if ((this._tenChuDe != value))
				{
					this.OntenChuDeChanging(value);
					this.SendPropertyChanging();
					this._tenChuDe = value;
					this.SendPropertyChanged("tenChuDe");
					this.OntenChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuDe_CauHoi", Storage="_CauHois", ThisKey="maChuDe", OtherKey="maChuDe")]
		public EntitySet<CauHoi> CauHois
		{
			get
			{
				return this._CauHois;
			}
			set
			{
				this._CauHois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = this;
		}
		
		private void detach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.ChuDe = null;
		}
	}
}
#pragma warning restore 1591
